server:
  port: ${PORT:8082}
  servlet:
    context-path: /client-service

spring:
  application:
    name: client-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  cloud:
    bus:
      enabled: true
      destination: config-be-parameters-topic
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_SERVER:localhost:9092}
          # Performance optimizations
          consumer-properties:
            fetch.min.bytes: 1024
            fetch.max.wait.ms: 100
            max.poll.records: 10
      bindings:
        springCloudBusInput:
          destination: config-parameters-topic
          # No group = broadcast to all instances
          consumer:
            auto-offset-reset: latest
  config:
    import: 'classpath:client-service-info.yaml'

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh # allow endpoint actuator/refresh
  endpoint:
    refresh:
      enabled: true

logging:
  level:
    org.springframework.cloud.bus: DEBUG
    org.springframework.cloud.stream: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.cloud.stream.config: DEBUG
    org.springframework.cloud.config: TRACE
    org.springframework.web.client: DEBUG
    org.springframework.http.client: TRACE
