version: '3'
services:
  elasticsearch:
    container_name: my-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    # volumes:
    #     - ~/data/my-elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'