server:
  port: 8080
camel:
  springboot:
    name: HelloWorldCamel

# binding health checks to a different port
management:
  port: 8081

# disable all management endpoints except health
endpoints:
  enabled: false
  health:
    enabled: true


# the application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

api:
  path: hello-world
spring:
  main:
    allow-bean-definition-overriding: true