#=================================================
# Log4j configuration - Message module
# 
#=================================================

#declare two logger
log4j.rootLogger=INFO,stdout,file,err
#log4j.rootLogger=INFO,stdout,file,err,warn
#log4j.rootLogger=WARN,err,MM_SOCK

#stdout appender
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{dd/MM/yyyy HH:mm:ss} %5p [%t] %L %c{1}: %m%n
log4j.appender.stdout.Threshold=INFO
#log4j.appender.stdout.Threshold=warn

# file appender
log4j.appender.file=uk.org.simonsite.log4j.appender.TimeAndSizeRollingAppender
log4j.appender.file.File=../log/full/full.log
log4j.appender.file.DatePattern='.'yyyy-MM-dd
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{dd/MM/yyyy HH:mm:ss.SSS} %5p [%t] %c{1}: %m%n
log4j.appender.file.Threshold=INFO
log4j.appender.file.CompressionAlgorithm=ZIP
log4j.appender.file.CompressionMinQueueSize=0
log4j.appender.file.MaxBackupIndex=3
log4j.appender.file.MaxRollFileCount=45
log4j.appender.file.maxFileSize=250MB
log4j.appender.file.DateRollEnforced=true
#log4j.appender.file.Threshold=warn

#Define appender MM_SOCK++++++++++++++++++++++++++++++++++++++++++
#Appender dung` de day log ve MM Client
log4j.appender.MM_SOCK=com.viettel.mmserver.log.appender.AdvanceSocketHubAppender
log4j.appender.MM_SOCK.port=8552
#zip
#log4j.appender.request=uk.org.simonsite.log4j.appender.TimeAndSizeRollingAppender
#log4j.appender.request.File=../log/full/full.log
#log4j.appender.request.Append=true
#log4j.appender.request.DatePattern='.'yyyy-MM-dd
#log4j.appender.request.MaxRollFileCount=10
#log4j.appender.request.DateRollEnforced=true
#log4j.appender.request.CompressionAlgorithm=ZIP
#log4j.appender.request.CompressionMinQueueSize=0
#log4j.appender.request.MaxBackupIndex=1
#log4j.appender.request.layout = org.apache.log4j.PatternLayout
#log4j.appender.request.layout.ConversionPattern=%d %-5p [%c Thread:%t] %m%n

#Gioi han so ket noi tu client den Server de xem log
log4j.appender.MM_SOCK.maxConnection=20

#So luong cac doi tuong LoggingEvent luu trong queue cua Appender.
#5000 doi tuong LoggingEvent co dung luong tam 2M - 5M 
log4j.appender.MM_SOCK.maxQueue=5000

#So luong log offline
log4j.appender.MM_SOCK.offlineMaxQueue=100
log4j.appender.MM_SOCK.Threshold=WARN
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++	

#Define appender for error Filtering & notify
log4j.appender.errorFilter=com.viettel.mmserver.log.appender.ErrorFilterJDBCAppender
log4j.appender.errorFilter.maxQueue=5000
log4j.appender.errorFilter.Threshold=WARN

### error file appender
log4j.appender.err=org.apache.log4j.DailyRollingFileAppender
log4j.appender.err.DatePattern='.'yyyy-MM-dd 
log4j.appender.err.File=../log/error/error.log
log4j.appender.err.layout=org.apache.log4j.PatternLayout
log4j.appender.err.layout.ConversionPattern=%d{dd/MM/yyyy HH:mm:ss.SSS} %5p [%t] %c{1}: %m%n
log4j.appender.err.Threshold=WARN

